# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui',
# licensing of 'mainwindow.ui' applies.
#
# Created: Thu Jan 24 23:15:42 2019
#      by: pyside2-uic  running on PySide2 5.12.0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(808, 845)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralWidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.imageView = QtWidgets.QLabel(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.imageView.sizePolicy().hasHeightForWidth())
        self.imageView.setSizePolicy(sizePolicy)
        self.imageView.setMinimumSize(QtCore.QSize(300, 425))
        self.imageView.setText("")
        self.imageView.setTextFormat(QtCore.Qt.PlainText)
        self.imageView.setScaledContents(False)
        self.imageView.setAlignment(QtCore.Qt.AlignCenter)
        self.imageView.setObjectName("imageView")
        self.verticalLayout_3.addWidget(self.imageView)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.prevButton = QtWidgets.QPushButton(self.centralWidget)
        self.prevButton.setMinimumSize(QtCore.QSize(100, 0))
        self.prevButton.setObjectName("prevButton")
        self.horizontalLayout.addWidget(self.prevButton)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.nextButton = QtWidgets.QPushButton(self.centralWidget)
        self.nextButton.setMinimumSize(QtCore.QSize(100, 0))
        self.nextButton.setObjectName("nextButton")
        self.horizontalLayout.addWidget(self.nextButton)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setObjectName("verticalLayout")
        self.processButton = QtWidgets.QPushButton(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.processButton.sizePolicy().hasHeightForWidth())
        self.processButton.setSizePolicy(sizePolicy)
        self.processButton.setMinimumSize(QtCore.QSize(200, 0))
        self.processButton.setMaximumSize(QtCore.QSize(300, 16777215))
        self.processButton.setObjectName("processButton")
        self.verticalLayout.addWidget(self.processButton)
        self.label_2 = QtWidgets.QLabel(self.centralWidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.idText = QtWidgets.QLineEdit(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.idText.sizePolicy().hasHeightForWidth())
        self.idText.setSizePolicy(sizePolicy)
        self.idText.setMinimumSize(QtCore.QSize(200, 0))
        self.idText.setMaximumSize(QtCore.QSize(300, 16777215))
        self.idText.setReadOnly(True)
        self.idText.setObjectName("idText")
        self.verticalLayout.addWidget(self.idText)
        self.label_3 = QtWidgets.QLabel(self.centralWidget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.versionText = QtWidgets.QLineEdit(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.versionText.sizePolicy().hasHeightForWidth())
        self.versionText.setSizePolicy(sizePolicy)
        self.versionText.setMinimumSize(QtCore.QSize(200, 0))
        self.versionText.setMaximumSize(QtCore.QSize(300, 16777215))
        self.versionText.setReadOnly(True)
        self.versionText.setObjectName("versionText")
        self.verticalLayout.addWidget(self.versionText)
        self.label = QtWidgets.QLabel(self.centralWidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.answerList = QtWidgets.QListWidget(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.answerList.sizePolicy().hasHeightForWidth())
        self.answerList.setSizePolicy(sizePolicy)
        self.answerList.setMinimumSize(QtCore.QSize(200, 0))
        self.answerList.setMaximumSize(QtCore.QSize(300, 16777215))
        self.answerList.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.answerList.setAlternatingRowColors(True)
        self.answerList.setObjectName("answerList")
        self.verticalLayout.addWidget(self.answerList)
        self.label_4 = QtWidgets.QLabel(self.centralWidget)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.scoreText = QtWidgets.QLineEdit(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scoreText.sizePolicy().hasHeightForWidth())
        self.scoreText.setSizePolicy(sizePolicy)
        self.scoreText.setMinimumSize(QtCore.QSize(200, 0))
        self.scoreText.setMaximumSize(QtCore.QSize(300, 16777215))
        self.scoreText.setReadOnly(True)
        self.scoreText.setObjectName("scoreText")
        self.verticalLayout.addWidget(self.scoreText)
        self.saveResultButton = QtWidgets.QPushButton(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.saveResultButton.sizePolicy().hasHeightForWidth())
        self.saveResultButton.setSizePolicy(sizePolicy)
        self.saveResultButton.setMinimumSize(QtCore.QSize(200, 0))
        self.saveResultButton.setMaximumSize(QtCore.QSize(300, 16777215))
        self.saveResultButton.setObjectName("saveResultButton")
        self.verticalLayout.addWidget(self.saveResultButton)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 808, 32))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menu_Open_recent = QtWidgets.QMenu(self.menuFile)
        self.menu_Open_recent.setObjectName("menu_Open_recent")
        self.menu_Settings = QtWidgets.QMenu(self.menubar)
        self.menu_Settings.setObjectName("menu_Settings")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_Open_image = QtWidgets.QAction(MainWindow)
        self.action_Open_image.setObjectName("action_Open_image")
        self.action_Open_PDF_collection = QtWidgets.QAction(MainWindow)
        self.action_Open_PDF_collection.setObjectName("action_Open_PDF_collection")
        self.action_Quit = QtWidgets.QAction(MainWindow)
        self.action_Quit.setObjectName("action_Quit")
        self.action_Set_template_file = QtWidgets.QAction(MainWindow)
        self.action_Set_template_file.setObjectName("action_Set_template_file")
        self.action_Set_grading_R_file = QtWidgets.QAction(MainWindow)
        self.action_Set_grading_R_file.setObjectName("action_Set_grading_R_file")
        self.action_Set_student_records_file = QtWidgets.QAction(MainWindow)
        self.action_Set_student_records_file.setObjectName("action_Set_student_records_file")
        self.menuFile.addAction(self.action_Open_PDF_collection)
        self.menuFile.addAction(self.action_Open_image)
        self.menuFile.addAction(self.menu_Open_recent.menuAction())
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.action_Quit)
        self.menu_Settings.addAction(self.action_Set_template_file)
        self.menu_Settings.addAction(self.action_Set_grading_R_file)
        self.menu_Settings.addAction(self.action_Set_student_records_file)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menu_Settings.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.action_Quit, QtCore.SIGNAL("triggered()"), MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "Answer sheet OMR", None, -1))
        self.prevButton.setText(QtWidgets.QApplication.translate("MainWindow", "Pre&vious", None, -1))
        self.nextButton.setText(QtWidgets.QApplication.translate("MainWindow", "&Next", None, -1))
        self.processButton.setText(QtWidgets.QApplication.translate("MainWindow", "&Process answer sheet", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("MainWindow", "Test ID:", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("MainWindow", "Version:", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("MainWindow", "Answers:", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("MainWindow", "Score:", None, -1))
        self.saveResultButton.setText(QtWidgets.QApplication.translate("MainWindow", "Save &result", None, -1))
        self.menuFile.setTitle(QtWidgets.QApplication.translate("MainWindow", "&File", None, -1))
        self.menu_Open_recent.setTitle(QtWidgets.QApplication.translate("MainWindow", "Open recent", None, -1))
        self.menu_Settings.setTitle(QtWidgets.QApplication.translate("MainWindow", "&Settings", None, -1))
        self.action_Open_image.setText(QtWidgets.QApplication.translate("MainWindow", "Open &image", None, -1))
        self.action_Open_image.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Ctrl+I", None, -1))
        self.action_Open_PDF_collection.setText(QtWidgets.QApplication.translate("MainWindow", "&Open PDF collection", None, -1))
        self.action_Open_PDF_collection.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Ctrl+O", None, -1))
        self.action_Quit.setText(QtWidgets.QApplication.translate("MainWindow", "&Quit", None, -1))
        self.action_Quit.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Ctrl+Q", None, -1))
        self.action_Set_template_file.setText(QtWidgets.QApplication.translate("MainWindow", "Set template file", None, -1))
        self.action_Set_template_file.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Ctrl+T", None, -1))
        self.action_Set_grading_R_file.setText(QtWidgets.QApplication.translate("MainWindow", "Set grading R file", None, -1))
        self.action_Set_grading_R_file.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Ctrl+R", None, -1))
        self.action_Set_student_records_file.setText(QtWidgets.QApplication.translate("MainWindow", "Set student records file", None, -1))

